# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Site Settings
locale                   : "en_US"
title                    : "Shunxing Fan (樊顺星)'s Homepage"
title_separator          : "-"
name                     : &name "Shunxing Fan (樊顺星)"
description              : &description "Research Assistant at MBZUAI, passionate about causality and AI for healthcare."
url                      : https://Shunxing-Fan.github.io  # the base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, leave empty for root
repository               : "Shunxing-Fan/Shunxing-Fan.github.io"
teaser                   : "teaser.png" # Add this image to /images/ folder
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "enabled"
talkmap_link             : false
comments:
  provider               : false

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : 
facebook:
  username               :
og_image                 : 

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-12345678-1" # Replace with your actual Google Analytics ID

# Site Author
author:
  name             : "Shunxing Fan (樊顺星)"
  avatar           : "profile.jpeg" # Add your profile picture to /images/ folder
  bio              : "Machine learning researcher, interested in causality and AI for healthcare."
  location         : "Abu Dhabi, UAE"
  employer         : "MBZUAI"
  email            : "shunxing.fan@gmail.com"
  googlescholar    : "https://scholar.google.com/citations?user=SbGcOdYAAAAJ&hl=en"
  github           : "Shunxing-Fan"
  linkedin         : 
  twitter          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
#   teaching:
#     output: true
#     permalink: /:collection/:path/
#   publications:
#     output: true
#     permalink: /:collection/:path/
#   portfolio:
#     output: true
#     permalink: /:collection/:path/
#   talks:
#     output: true
#     permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
#   # _teaching
#   - scope:
#       path: ""
#       type: teaching
#     values:
#       layout: single
#       author_profile: true
#       share: true
#       comments: true
#   # _publications
#   - scope:
#       path: ""
#       type: publications
#     values:
#       layout: single
#       author_profile: true
#       share: true
#       comments: true
#   # _portfolio
#   - scope:
#       path: ""
#       type: portfolio
#     values:
#       layout: single
#       author_profile: true
#       share: true
#   # _talks
#   - scope:
#       path: ""
#       type: talks
#     values:
#       layout: talk
#       author_profile: true
#       share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Dubai # Set to your timezone

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Theme
theme: jekyll-theme-cayman
